### ISSUE TITLE
File creation and deletion not detected

### ISSUE THREAD

**Issue by paulbriton** [ptlis/diff-parser#3]
Hi, there is an issue in detecting file modification type. 

I've tried with diff containing added, changed and removed files but all files are detected as changed. I think the major issue comes from the `UnifiedDiffTokenizer` and the `HUNK_START_REGEX` which isn't working with SVN 1.8. 

Moreover there is also an issue with the latest SVN version (1.9) which uses (nonexistent) for new files, not (revision 0).

**Comment by ptlis** [comment]
Hi Paul, thanks for the bug report.

Having generated some test diffs with SVN 1.8 and 1.9 I can replicate the 'revision x' => 'nonexistent' issue (with creations and deletions) in 1.9. Could you test this by switching the version to dev-master, which should have fixes for both cases.

On the other hand I was unable to find any problems in processing diffs from SVN 1.8 - it may be that the generated patches are too trivial to trigger the bug. If this is the case providing me with an example patch file would be the quickest way to narrow this down. If the only example you have is for something proprietary we could share the example privately and I'd be able to create an anonymised equivalent for testing purposes.

**Comment by paulbriton** [comment]
Thank's for your bug fix, it's working perfectly with SVN 1.9 ! 

[Here](https://gist.github.com/paulbriton/0aad240301a7a469220c91674c502c94) is a diff generated with SVN 1.8. If you iterate over files and call the `getOperation()` method, you'll see that the only operation detected is `changed`.

**Comment by ptlis** [comment]
I was able to replicate this bug using the patch you provided. Digging into this I identified some inconsistencies in how the library processed one line and mutli line file creations/deletions that seems to have been the cause for this.

Could you try again with the master branch and confirm that this fix is correct.

**Comment by paulbriton** [comment]
Everything seems to be OK on both SVN versions ! I'll let you know if I come across another issue. 
Thank's a lot for your reactivity and your help !

**Comment by ptlis** [comment]
No worries :+1:

I've tagged a new release (0.6.0) so you can depend upon a stable release.
