### ISSUE TITLE
PHP 5.6 Support

### ISSUE THREAD

**Issue by juanmrad** [ptlis/diff-parser#4]
Your project used to support php 5.6 on version 0.6.0 currently master only supports php 7+ is it possible to create a new branch where php 5.6 is still supported I need to create a PR with a fix on it and my current project is in php 5.6 I will also create the PR against master so the fix is in both branches.

**Comment by ptlis** [comment]
Sure! If you could address the comments I've left on your PR I'll create a branch to maintain the 0.6 release with PHP >= 5.3 support.

**Comment by ptlis** [comment]
I'm closing this as I don't see supporting PHP < 7.2 as a priority (PHP 7.1's EOL being less than a month away).
