### ISSUE TITLE
EOL CRLF in UnifiedDiffTokenizer.php causes an error with preg_match()

### ISSUE THREAD

**Issue by dmrsol** [ptlis/diff-parser#7]
It's appear on windows system with git param core.autocrlf = true. Pattern HUNK_START_REGEX in one line helped

**Comment by ptlis** [comment]
Hi dmrsol, could you provide an example diff? 

I tried testing this via changing the line separator in a diff file from LF to CRLF but couldn't reproduce this issue. Could you provide me with an example patch file that demonstrates this issue?

I assume that you're running PHP from Windows too?

**Comment by dmrsol** [comment]
It's not for diff. Git convert LF to CRLF when checking out. So, CRLF appears in src/Parse/UnifiedDiffTokenizer.php

> I assume that you're running PHP from Windows too?

Yes

**Comment by ptlis** [comment]
I'm struggling to understand exactly what the issue is - could you provide me with steps to reproduce this?

**Comment by dmrsol** [comment]
Ok, i'll try :)

1. I'm on Windows system, with git config core.autocrlf = true. It means, that git convert LF to CRLF when checking out files
2. After `composer require ptlis/diff-parser`, composer downloads files and `vendor/ptlis/diff-parser/src/Parse/UnifiedDiffTokenizer.php` has CRLF line endings
3. Try to parse any diff
4. Error - `' in C:\server\projects\www\public\vendor\ptlis\diff-parser\src\Parse\UnifiedDiffTokenizer.php on line 239`

You can reproduce this by changing eol of /src/Parse/UnifiedDiffTokenizer.php to CRLF manualy. And then try to parse any diff.

**Comment by ptlis** [comment]
Great, I've been able to reproduce this issue on my Linux system and on Travis. 

I think I've found the solution, could you try the with the `bugfix/fix-git-checkout-autocrlf` branch and confirm whether this fix works on Windows?

**Comment by dmrsol** [comment]
Thanks! Fix works

**Comment by ptlis** [comment]
:+1:
